server:
  port: 8082

spring:
  freemarker:
    suffix: .html

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456

smart:
  sso:
    #服务端地址
    server-url: http://server.smart-sso.com:8080
    #客户端应用信息
    app-key: demo2
    app-secret: 123456