server:
  port: 8081

spring:
  freemarker:
    suffix: .html

#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      password: 123456

smart:
  sso:
    #服务端地址
    server-url: http://server.smart-sso.com:8080
    #客户端密钥信息
    client-id: 1001
    client-secret: kpA1y7k1uyrcoGhrKvA1Ag==